CREATE TABLE Athletes (
    ID SERIAL PRIMARY KEY,
    FirstName VARCHAR(50) NOT NULL,
    LastName VARCHAR(50) NOT NULL,
    DateOfBirth DATE NOT NULL,
    Gender CHAR(1) CHECK (Gender IN ('M', 'F')) NOT NULL
);

CREATE TABLE Sports (
    ID SERIAL PRIMARY KEY,
    Name VARCHAR(50) NOT NULL
);

CREATE TABLE Competitions (
    ID SERIAL PRIMARY KEY,
    Name VARCHAR(100) NOT NULL,
    DateHeld DATE NOT NULL,
    Venue VARCHAR(100) NOT NULL,
    SportID INT REFERENCES Sports(ID) ON DELETE CASCADE
);

CREATE TABLE Results (
    ID SERIAL PRIMARY KEY,
    CompetitionID INT REFERENCES Competitions(ID) ON DELETE CASCADE,
    AthleteID INT REFERENCES Athletes(ID) ON DELETE CASCADE,
    Result VARCHAR(50) NOT NULL
);
